# How to use Pandas?
## Part - 7

In [1]:
import numpy as np
import pandas as pd

Set `tips.csv` DataFrame

In [2]:
tips_df = pd.read_csv('DATA/tips.csv')

In [3]:
tips_df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [4]:
tips_df['Total_pay'] = tips_df['total_bill'] + tips_df['tip']

To change **Index** in DataFrame to other features.

In [5]:
tips_df.set_index('Payment ID', inplace=True)

Now, we can search in DataFrame with new index.

In [6]:
tips_df.loc["Sun2251"]

total_bill                     24.59
tip                             3.61
sex                           Female
smoker                            No
day                              Sun
time                          Dinner
size                               4
price_per_person                6.15
Payer Name              Tonya Carter
CC Number           4832732618637221
Total_pay                       28.2
Name: Sun2251, dtype: object

In [7]:
tips_df.iloc[10]

total_bill                  10.27
tip                          1.71
sex                          Male
smoker                         No
day                           Sun
time                       Dinner
size                            2
price_per_person             5.14
Payer Name          William Riley
CC Number            566287581219
Total_pay                   11.98
Name: Sun2546, dtype: object

Conditional Operation in DataFrame

In [8]:
tips_df[tips_df['total_bill'] > 15].head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Total_pay
Payment ID,,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,18.00
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,24.51
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,26.99
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,28.20
Sun9679,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,30.00

In [ ]:
tips_female_total_pay_df = tips_df[(tips_df['sex'] == 'Female') & (tips_df['Total_pay'] >= 20)]

In [14]:
tips_female_total_pay_df.describe().T

,count,mean,std,min,25%,50%,75%,max
total_bill,40.0,2.453725e+01,7.142808e+00,1.632000e+01,1.874500e+01,2.258500e+01,2.742750e+01,4.430000e+01
tip,40.0,3.619500e+00,1.082561e+00,1.360000e+00,3.000000e+00,3.500000e+00,4.225000e+00,6.500000e+00
size,40.0,2.975000e+00,1.120611e+00,2.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,6.000000e+00
price_per_person,40.0,8.857000e+00,2.677050e+00,4.510000e+00,6.195000e+00,8.750000e+00,1.054000e+01,1.477000e+01
CC Number,40.0,2.808240e+15,2.419846e+15,6.046330e+10,4.912704e+12,3.762231e+15,5.166581e+15,6.011787e+15
Total_pay,40.0,2.815675e+01,7.640175e+00,2.000000e+01,2.174750e+01,2.595000e+01,3.234500e+01,4.811000e+01

In [15]:
tips_male_total_pay_df = tips_df[(tips_df['sex'] == 'Male') | (tips_df['Total_pay'] >= 20)]

In [16]:
tips_male_total_pay_df.info()

<class 'pandas.DataFrame'>
Index: 197 entries, Sun4608 to Thur672
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        197 non-null    float64
 1   tip               197 non-null    float64
 2   sex               197 non-null    str
 3   smoker            197 non-null    str
 4   day               197 non-null    str
 5   time              197 non-null    str
 6   size              197 non-null    int64
 7   price_per_person  197 non-null    float64
 8   Payer Name        197 non-null    str
 9   CC Number         197 non-null    int64
 10  Total_pay         197 non-null    float64
dtypes: float64(4), int64(2), str(5)
memory usage: 22.5+ KB

For search several values in feature of DataFrame, as follow:

In [20]:
tips_df[(tips_df['day'].isin(['Sat','Sun'])) & (tips_df['Total_pay'] >= 20) & (tips_df['size'] > 3)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Total_pay
Payment ID,,,,,,,,,,,
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,28.20
Sun9679,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,30.00
Sun8157,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3514785077705092,30.00
Sun6686,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4577817359320969,40.26
Sun2971,18.43,3.00,Male,No,Sun,Dinner,4,4.61,Joshua Jones,6011163105616890,21.43
Sat239,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,47.00
Sat907,17.81,2.34,Male,No,Sat,Dinner,4,4.45,Robert Perkins,30502930499388,20.15
Sat4947,18.35,2.50,Male,No,Sat,Dinner,4,4.59,Danny Santiago,630415546013,20.85
Sat6649,20.69,2.45,Female,No,Sat,Dinner,4,5.17,Amber Francis,377742985258914,23.14
Sun2274,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,503846761263,36.00
Sun9677,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,38.40
Sun6165,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4291280793094374,40.01
Sun9470,25.56,4.34,Male,No,Sun,Dinner,4,6.39,Ronald Owens,6569607991983380,29.90
Sat8903,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,349793629453226,41.01
Sat8139,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,55.00
Sat4178,18.29,3.76,Male,Yes,Sat,Dinner,4,4.57,Chad Hart,580171498976,22.05
Sun22,29.93,5.07,Male,No,Sun,Dinner,4,7.48,Shawn Blake,4689079711213722,35.00
Sun8670,24.55,2.00,Male,No,Sun,Dinner,4,6.14,Todd Patterson,4416804908942159,26.55
Sun5814,19.77,2.00,Male,No,Sun,Dinner,4,4.94,James Smith,213169731428229,21.77
Sun9176,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4210875236164664,34.99
Sun7518,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,53.17
Sun7015,25.00,3.75,Female,No,Sun,Dinner,4,6.25,Laura Robles,213158685144262,28.75
Sun245,21.50,3.50,Male,No,Sun,Dinner,4,5.38,Travis Gonzalez,3527668419764685,25.00
Sun3719,31.71,4.50,Male,No,Sun,Dinner,4,7.93,Michael Lawson,3566285921227119,36.21
Sun7544,34.65,3.68,Male,Yes,Sun,Dinner,4,8.66,James Hebert DDS,676168737648,38.33
Sun6059,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,4718501859162,29.67
Sun5842,20.69,5.00,Male,No,Sun,Dinner,5,4.14,Joseph Howell,30362407455623,25.69
Sun9987,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4792882899700988,32.46
Sat4505,38.73,3.00,Male,Yes,Sat,Dinner,4,9.68,Ricky Ramirez,347817964484033,41.73
Sat6735,25.89,5.16,Male,Yes,Sat,Dinner,4,6.47,Christopher Li,6011962464150569,31.05
Sat4590,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,57.33
Sat7320,28.15,3.00,Male,Yes,Sat,Dinner,5,5.63,Shawn Barnett PhD,4590982568244,31.15
Sat8863,30.14,3.09,Female,Yes,Sat,Dinner,4,7.54,Shelby House,502097403252,33.23
Sat4319,20.45,3.00,Male,No,Sat,Dinner,4,5.11,Robert Bradley,213141668145910,23.45
Sat7872,24.01,2.00,Male,Yes,Sat,Dinner,4,6.00,Michael Osborne,4258682154026,26.01