# How to use Pandas?
## PArt - 9

In [1]:
import numpy as np
import pandas as pd

In [2]:
tips_df = pd.read_csv('DATA/tips.csv')

In [3]:
tips_df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [4]:
tips_df.set_index('Payment ID', inplace=True)

We can **Sort** **DataFrame** based on several **Features**

In [5]:
tips_df.sort_values(['tip', 'size'], ascending=True)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sat3455,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267
Sat4801,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887
Fri3780,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392
Sat5032,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
...,...,...,...,...,...,...,...,...,...,...
Thur1025,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508
Sat8139,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595
Sat239,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808
Sat4590,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212
Sat1954,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236

Find **Maximum** value and its index for each feature.

In [6]:
tips_df['tip'].max()

np.float64(10.0)

In [7]:
tips_df['tip'].idxmax()

'Sat1954'

Find **Minimum** value and its index for each feature.

In [8]:
tips_df['tip'].min()

np.float64(1.0)

In [9]:
tips_df['tip'].idxmin()

'Sat3455'

In [10]:
tips_df.loc[f'{tips_df['total_bill'].idxmax()}']

total_bill                     50.81
tip                             10.0
sex                             Male
smoker                           Yes
day                              Sat
time                          Dinner
size                               3
price_per_person               16.94
Payer Name             Gregory Clark
CC Number           5473850968388236
Name: Sat1954, dtype: object

Display the extent of **Direct** or **Inverse** relationships of features within a **DataFrame**

In [11]:
tips_df.corr(numeric_only=True)

                  total_bill       tip      size  price_per_person  CC Number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
CC Number           0.104576  0.110857 -0.030239          0.135240   1.000000

**Count** the values for each feature in **DataFrame**

In [12]:
tips_df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [13]:
tips_df['day'].unique()

<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str

To find **Duplicated** rows

In [14]:
tips_df.duplicated()

Payment ID
Sun2959    False
Sun4608    False
Sun4458    False
Sun5260    False
Sun2251    False
           ...
Sat2657    False
Sat1766    False
Sat3880    False
Sat17      False
Thur672    False
Length: 244, dtype: bool

Drop **Duplicated** rows

In [15]:
tips_df.drop_duplicates()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221
...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139

For conditional order and find to values between two values

In [16]:
tips_df[tips_df['total_bill'].between(15,20)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun6820,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377
Sun1300,15.42,1.57,Male,No,Sun,Dinner,2,7.71,Chad Harrington,577040572932
Sun2971,18.43,3.00,Male,No,Sun,Dinner,4,4.61,Joshua Jones,6011163105616890
Sun2998,16.29,3.71,Male,No,Sun,Dinner,3,5.43,John Pittman,6521340257218708
...,...,...,...,...,...,...,...,...,...,...
Fri6665,16.27,2.50,Female,Yes,Fri,Lunch,2,8.14,Whitney Arnold,3579111947217428
Sat6334,15.69,3.00,Male,Yes,Sat,Dinner,3,5.23,Jason Parks,4812333796161
Sat7220,15.53,3.00,Male,Yes,Sat,Dinner,2,7.76,Tracy Douglas,4097938155941930
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139

To show `n` largest in feature of DataFrame

In [17]:
tips_df['tip'].nlargest(10)

Payment ID
Sat1954     10.00
Sat4590      9.00
Sat239       7.58
Sat8139      6.73
Thur1025     6.70
Sun6059      6.50
Sat3374      6.50
Sun9677      6.00
Sat2657      5.92
Thur9003     5.85
Name: tip, dtype: float64

To show `n` smallest in feature of DataFrame

In [18]:
tips_df['tip'].nsmallest(10)

Payment ID
Sat3455     1.00
Fri3780     1.00
Sat4801     1.00
Sat5032     1.00
Sun2959     1.01
Sat6983     1.10
Sat2929     1.17
Sat5056     1.25
Thur6600    1.25
Sat4615     1.25
Name: tip, dtype: float64

Create a random sample of DataFrame

In [20]:
tips_df.sample(frac=0.1)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Fri5959,13.42,1.58,Male,Yes,Fri,Lunch,2,6.71,Ronald Vaughn DVM,341503466406403
Sat6750,15.81,3.16,Male,Yes,Sat,Dinner,2,7.90,David Hall,502004138207
Sat1709,17.92,4.08,Male,No,Sat,Dinner,2,8.96,Thomas Rice,4403296224639756
Sun2274,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,503846761263
Sat2353,20.29,3.21,Male,Yes,Sat,Dinner,2,10.14,Anthony Mclean,347614304015027
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842
Sun8594,13.81,2.00,Male,No,Sun,Dinner,2,6.90,Charles Newton,5552793481414044
Thur6245,13.16,2.75,Female,No,Thur,Lunch,2,6.58,Lindsey Meyer,676239597203
Sun8746,17.31,3.50,Female,No,Sun,Dinner,2,8.65,Kayla Stone,379494319310858
Sat2265,11.02,1.98,Male,Yes,Sat,Dinner,2,5.51,Joseph Hart,180046232326178
Sun9677,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186
Sat9618,20.29,2.75,Female,No,Sat,Dinner,2,10.14,Natalie Gardner,5448125351489749
Sat4056,18.69,2.31,Male,No,Sat,Dinner,3,6.23,Brandon Bradley,4427601595688633
Sat6548,14.73,2.20,Female,No,Sat,Dinner,2,7.36,Ashley Harris,501828723483
Sat4615,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3534021246117605
Fri5700,22.49,3.50,Male,No,Fri,Dinner,2,11.24,Earl Horn,6011849326227398
Fri4106,11.35,2.50,Female,Yes,Fri,Dinner,2,5.68,Lori Lynch,38558279384492
Thur9002,16.43,2.30,Female,No,Thur,Lunch,2,8.22,Linda Jones,6542729219645658
Sat3030,13.81,2.00,Male,Yes,Sat,Dinner,2,6.90,Ryan Hernandez,4766834726806
Sat2124,11.61,3.39,Male,No,Sat,Dinner,2,5.80,James Taylor,6011482917327995
Thur1446,19.08,1.50,Male,No,Thur,Lunch,2,9.54,Seth Sexton,213113680829581
Thur8551,11.38,2.00,Female,No,Thur,Lunch,2,5.69,Christine Perkins,3548391118913991
Thur3906,17.47,3.50,Female,No,Thur,Lunch,2,8.74,Kayla Rios,5233918213804470
Sun1300,15.42,1.57,Male,No,Sun,Dinner,2,7.71,Chad Harrington,577040572932