# How to use Pandas?
## Part - 14

In [1]:
import numpy as np
import pandas as pd

**Create DateTime Series**

In [12]:
my_date_ser = pd.Series(['Nov 3, 1990','2000-01-05', None])

In [13]:
my_date_ser

0    Nov 3, 1990
1     2000-01-05
2            NaN
dtype: str

In [14]:
pd.to_datetime(my_date_ser, format='mixed')

0   1990-11-03
1   2000-01-05
2          NaT
dtype: datetime64[us]

Special format date

In [15]:
mydate = '10--11--2023'

In [17]:
pd.to_datetime(mydate, format="%d--%m--%Y")

Timestamp('2023-11-10 00:00:00')

Now, Exercise with DataFrame

In [21]:
date_df = pd.read_csv("DATA/RetailSales_BeerWineLiquor.csv")

In [22]:
date_df.head()

         DATE  MRTSSM4453USN
0  1992-01-01           1509
1  1992-02-01           1541
2  1992-03-01           1597
3  1992-04-01           1675
4  1992-05-01           1822

In [23]:
date_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DATE           340 non-null    str
 1   MRTSSM4453USN  340 non-null    int64
dtypes: int64(1), str(1)
memory usage: 5.4 KB

Two exist methods for convert DateString to 

First

In [24]:
date_df['DATE'] = pd.to_datetime(date_df['DATE'])

In [25]:
date_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DATE           340 non-null    datetime64[us]
 1   MRTSSM4453USN  340 non-null    int64
dtypes: datetime64[us](1), int64(1)
memory usage: 5.4 KB

Second

In [27]:
date_df = pd.read_csv("DATA/RetailSales_BeerWineLiquor.csv", parse_dates=[0])

In [28]:
date_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DATE           340 non-null    datetime64[us]
 1   MRTSSM4453USN  340 non-null    int64
dtypes: datetime64[us](1), int64(1)
memory usage: 5.4 KB

In [41]:
date_df = date_df.set_index('DATE')

In [42]:
date_df.resample(rule='YE').sum()

            MRTSSM4453USN
DATE
1992-12-31          21687
1993-12-31          21538
1994-12-31          22101
1995-12-31          22007
1996-12-31          23157
1997-12-31          24081
1998-12-31          25382
1999-12-31          26476
2000-12-31          28507
2001-12-31          29621
2002-12-31          29894
2003-12-31          30469
2004-12-31          32189
2005-12-31          33567
2006-12-31          36016
2007-12-31          38128
2008-12-31          39504
2009-12-31          40245
2010-12-31          41401
2011-12-31          42392
2012-12-31          44365
2013-12-31          46076
2014-12-31          48286
2015-12-31          50550
2016-12-31          53213
2017-12-31          55232
2018-12-31          57968
2019-12-31          59673
2020-12-31          19690