# How to use Pandas?
## Part - 16

In [17]:
import numpy as np
import pandas as pd

In [3]:
sales_df = pd.read_csv('DATA/Sales_Funnel_CRM.csv')

In [6]:
sales_df.head()

,Account Number,Company,Contact,Account Manager,Product,Licenses,Sale Price,Status
0,2123398,Google,Larry Pager,Edward Thorp,Analytics,150,2100000,Presented
1,2123398,Google,Larry Pager,Edward Thorp,Prediction,150,700000,Presented
2,2123398,Google,Larry Pager,Edward Thorp,Tracking,300,350000,Under Review
3,2192650,BOBO,Larry Pager,Edward Thorp,Analytics,150,2450000,Lost
4,420496,IKEA,Elon Tusk,Edward Thorp,Analytics,300,4550000,Won

The **Pivot** function is a famous, because this function have many attributes for modify **DataFrame**

In [9]:
pd.pivot(sales_df, index='Company', columns='Product', values='Licenses')

Product       Analytics  GPS Positioning  Prediction  Tracking
Company
 Google           150.0              NaN       150.0     300.0
ATT                 NaN              NaN       150.0     150.0
Apple             300.0              NaN         NaN       NaN
BOBO              150.0              NaN         NaN       NaN
CVS Health          NaN              NaN         NaN     450.0
Cisco             300.0            300.0         NaN       NaN
Exxon Mobile      150.0              NaN         NaN       NaN
IKEA              300.0              NaN         NaN       NaN
Microsoft           NaN              NaN         NaN     300.0
Salesforce        750.0              NaN         NaN       NaN
Tesla Inc.        300.0              NaN       150.0       NaN
Walmart           150.0              NaN         NaN       NaN

In [10]:
pd.pivot_table(sales_df, values=['Sale Price', 'Licenses'], index='Company', aggfunc='sum')

              Licenses  Sale Price
Company
 Google            600     3150000
ATT                300     1050000
Apple              300     4550000
BOBO               150     2450000
CVS Health         450      490000
Cisco              600     4900000
Exxon Mobile       150     2100000
IKEA               300     4550000
Microsoft          300      350000
Salesforce         750     7000000
Tesla Inc.         450     3500000
Walmart            150     2450000

In [15]:
pd.pivot_table(sales_df, index=['Account Manager', 'Contact'], values='Sale Price', aggfunc='sum', columns='Product', fill_value=0)

Product                       Analytics  GPS Positioning  Prediction  Tracking
Account Manager Contact
Claude Shannon  Cindy Phoner    6650000                0      700000    350000
                Emma Gordian   11550000           350000           0    490000
Edward Thorp    Elon Tusk       7350000                0      700000         0
                Larry Pager     4550000                0      700000    350000
                Will Grates     2450000                0           0    350000

In [18]:
pd.pivot_table(sales_df, index=['Account Manager', 'Contact', 'Product'], values='Sale Price', aggfunc=[np.sum, np.mean], fill_value=0)

                                                    sum       mean
                                             Sale Price Sale Price
Account Manager Contact      Product
Claude Shannon  Cindy Phoner Analytics          6650000  3325000.0
                             Prediction          700000   700000.0
                             Tracking            350000   350000.0
                Emma Gordian Analytics         11550000  5775000.0
                             GPS Positioning     350000   350000.0
                             Tracking            490000   490000.0
Edward Thorp    Elon Tusk    Analytics          7350000  3675000.0
                             Prediction          700000   700000.0
                Larry Pager  Analytics          4550000  2275000.0
                             Prediction          700000   700000.0
                             Tracking            350000   350000.0
                Will Grates  Analytics          2450000  2450000.0
                             Tracking            350000   350000.0